name: hcntm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.22
  - scipy>=1.9
  - scikit-learn>=1.1
  - pip
  - pip:
    # Additional pip-only packages could be listed here
    - -r requirements.txt